//! Builds the Tauri capability that lets the app talk to the backend.
//!
//! The backend URL is not written into the repo: it comes from `VITE_BACKEND_URL`, the
//! same variable the frontend uses as its API base, so one value drives both. `build.rs`
//! includes this file and writes the result to `capabilities/backend-url.json`
//! (gitignored); `tests/backend_scope_tests.rs` includes it to test the logic.

/// Used when nothing is configured, matching the frontend's own fallback.
pub const DEFAULT_BACKEND_URL: &str = "http://localhost:3000";

/// Name of the variable shared with the frontend (Vite).
pub const BACKEND_URL_VAR: &str = "VITE_BACKEND_URL";

/// Reduces a configured URL to its origin (`scheme://host[:port]`), refusing anything
/// that is not a plain http(s) URL. The origin ends up inside a JSON file, so characters
/// that could break out of the string are rejected rather than escaped.
pub fn allowed_origin(raw: &str) -> Result<String, String> {
    let url = raw.trim();
    let (scheme, rest) = if let Some(rest) = url.strip_prefix("https://") {
        ("https", rest)
    } else if let Some(rest) = url.strip_prefix("http://") {
        ("http", rest)
    } else {
        return Err(format!(
            "{BACKEND_URL_VAR} must start with http:// or https://, got {url:?}"
        ));
    };

    let authority = rest.split(['/', '?', '#']).next().unwrap_or("");
    if authority.is_empty() {
        return Err(format!("{BACKEND_URL_VAR} has no host: {url:?}"));
    }
    let valid = |c: char| c.is_ascii_alphanumeric() || matches!(c, '.' | '-' | ':' | '[' | ']');
    if !authority.chars().all(valid) {
        return Err(format!(
            "{BACKEND_URL_VAR} host contains unsupported characters: {authority:?}"
        ));
    }
    Ok(format!("{scheme}://{authority}"))
}

/// The capability file: the main window may fetch from `origin` and nowhere else.
/// Scopes of `http:default` are merged with the plain entry in `default.json`.
pub fn capability_json(origin: &str) -> String {
    format!(
        r#"{{
  "$schema": "../gen/schemas/desktop-schema.json",
  "identifier": "backend-url",
  "description": "Generated by build.rs from VITE_BACKEND_URL. Do not edit or commit. The only place http:default is granted.",
  "windows": ["main"],
  "permissions": [
    {{
      "identifier": "http:default",
      "allow": [{{ "url": "{origin}/*" }}]
    }}
  ]
}}
"#
    )
}

/// Reads `key` from the contents of a dotenv file (`KEY=value`, optional quotes,
/// `#` comments). The last assignment wins, as in Vite.
pub fn dotenv_value(contents: &str, key: &str) -> Option<String> {
    let mut found = None;
    for line in contents.lines() {
        let line = line.trim();
        if line.starts_with('#') {
            continue;
        }
        let line = line.strip_prefix("export ").unwrap_or(line);
        if let Some((k, v)) = line.split_once('=') {
            if k.trim() == key {
                let v = v.trim();
                let v = v
                    .strip_prefix('"')
                    .and_then(|v| v.strip_suffix('"'))
                    .or_else(|| v.strip_prefix('\'').and_then(|v| v.strip_suffix('\'')))
                    .unwrap_or(v);
                found = Some(v.to_string());
            }
        }
    }
    found.filter(|v| !v.is_empty())
}

/// Picks the backend URL: the process environment first, then dotenv file contents in
/// priority order (e.g. `.env.local` before `.env`), then the localhost default.
pub fn resolve_backend_url(env_value: Option<String>, dotenv_files: &[String]) -> String {
    env_value
        .filter(|v| !v.trim().is_empty())
        .or_else(|| {
            dotenv_files
                .iter()
                .find_map(|contents| dotenv_value(contents, BACKEND_URL_VAR))
        })
        .unwrap_or_else(|| DEFAULT_BACKEND_URL.to_string())
}
